name: Deploy to Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.frontend
          build-args:
            -DATABASE_URL=${{ secrets.DATABASE_URL}}
          push: true
          tags: gourav9211/todo-app-ws:${{ github.sha }}
